### 1. 3 배열의 연산(Operation)

In [2]:
import numpy as np

- 벡터화 연산

In [2]:
x = np.arange(1, 100001)
y = np.arange(100001, 200001)

In [18]:
%%time
z = np.empty_like(x)
for i in range(100000):
    z[i] = x[i] + y[i]


CPU times: total: 46.9 ms
Wall time: 42 ms


In [19]:
%%time
z = x + y

CPU times: total: 0 ns
Wall time: 0 ns


In [20]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,4])
a == b

array([False, False, False,  True])

In [21]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [22]:
10 ** a

array([   10,   100,  1000, 10000], dtype=int32)

In [23]:
5 * a 

array([ 5, 10, 15, 20])

In [24]:
5 + a

array([6, 7, 8, 9])

- 차원 축소연산

In [26]:
x = np.arange(1, 5)
np.sum(x)

10

In [27]:
x.sum()

10

In [28]:
x.min(), x.max(), x.mean()   # 최소, 최대, 평균

(1, 4, 2.5)

In [29]:
# 대표값 : 평균, 중앙,값
np.mean(x), np.median(x)

(2.5, 2.5)

In [31]:
# 통계
np.var(x), np.std(x)

(1.25, 1.118033988749895)

In [33]:
# 최소값, 최대값의 인덱스
x.argmin(),x.argmax()

(0, 3)

- all / any

In [34]:
a= np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
# 모든 원소의 합과 평균
np.sum(a), np.mean(a)

(21, 3.5)

In [36]:
# axis = 0, 각 좌표(row, col)에서 row를 변경시키가면서 액세스
np.sum(a, axis=0), np.mean(a, axis=0)

(array([5, 7, 9]), array([2.5, 3.5, 4.5]))

In [38]:
# axis = 1, 각 좌표(row, col)에서 col를 변경시키가면서 액세스
np.sum(a, axis=1), np.mean(a, axis=1)

(array([ 6, 15]), array([2., 5.]))

In [39]:
b = np.arange(1, 13).reshape(2, 2, -1)
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [40]:
np.sum(b, axis=0)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [41]:
np.sum(b, axis=1)

array([[ 5,  7,  9],
       [17, 19, 21]])

In [42]:
np.sum(b, axis=2)

array([[ 6, 15],
       [24, 33]])

- 연습문제 3.3.1

In [45]:
np.random.seed = 2023
x = np.round(np.random.random(30).reshape(5, 6) * 10, 4)
x

array([[9.8916, 7.7511, 4.4625, 0.707 , 8.1419, 4.4939],
       [4.693 , 8.977 , 1.6194, 4.2136, 2.8304, 1.9354],
       [5.2292, 1.4777, 0.3508, 8.8447, 5.6845, 0.8739],
       [8.5835, 2.338 , 8.292 , 7.8042, 5.1878, 2.1984],
       [9.5821, 7.8697, 3.0919, 2.8166, 0.6013, 0.7647]])

In [56]:
# 전체의 최댓값
x.max() 


9.8916

In [50]:
# 2. 각 행의 합
x.sum(axis=1)

array([35.448 , 24.2688, 22.4608, 34.4039, 24.7263])

In [51]:
# 3. 각 행의 최댓값
x.max(axis=1)

array([9.8916, 8.977 , 8.8447, 8.5835, 9.5821])

In [57]:
# 4. 각 열의 평균
x.mean(axis=0)

array([7.59588, 5.6827 , 3.56332, 4.87722, 4.48918, 2.05326])

In [58]:
# 5. 각 열의 최솟값
x.min(axis=0)

array([4.693 , 1.4777, 0.3508, 0.707 , 0.6013, 0.7647])

- 정렬(sort)

In [59]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [60]:
np.sort(a)      #default axis=1

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [61]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [63]:
# 내림차순 정렬, axis=1인 경우
np.sort(a,axis=1)[:, ::-1]

array([[ 7,  5,  4,  3],
       [12, 11,  9,  1],
       [15, 14,  2,  1]])

In [64]:
# 내림차순 정렬, axis=0인 경우
np.sort(a,axis=0)[::-1, :]

array([[ 4, 15, 11, 14],
       [ 2, 12,  5,  9],
       [ 1,  3,  1,  7]])

In [65]:
# sort() method는 자기 파괴적(in-place)
a.sort(axis=1)

In [66]:
a


array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [70]:
a = np.array([42, 38, 12,25])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [71]:
a[j]

array([12, 25, 38, 42])

- 연습문제 3.3.2

In [3]:
x = np.array([[1,2,3,4],           # 학번
     [46,99,100,71],               # 영어
     [81,59,90,100]])              # 수학
x




array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [4]:
# 영어 성적을 argsort() 하여 인덱스를 구함
indices = np.argsort(x[1])
indices

array([0, 3, 1, 2], dtype=int64)

In [5]:
# 인덱스를 내림차순으로 정렬
indices[::-1]

array([2, 1, 3, 0], dtype=int64)

In [6]:
# 모든 행을 영어성적 내림차순으로 정렬
x[:, indices[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [7]:
# 한 줄로 
x[:,np.argsort(x[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])