### 1.5 난수 발생과 카운팅

In [2]:
import numpy as np

- 시드 설정

In [5]:
np.random.seed(2023)
np.random.random(5)

array([0.3219883 , 0.89042245, 0.58805226, 0.12659609, 0.14134122])

- 데이터의 순서 바꾸기


In [7]:
x = np.arange(10)
np.random.shuffle(x)    # x 데이터의 순서를 바꿈
x

array([4, 6, 5, 3, 2, 8, 9, 7, 0, 1])

- 데이터의 샘플링

In [11]:
np.random.choice(5, 5, replace=False)       # 비복원 추출

array([3, 2, 0, 4, 1])

In [21]:
np.random.choice(5, 5, replace=True)        # 복원 추출

array([0, 0, 2, 0, 1])

In [22]:
x = np.random.randint(1, 100, 10)            # 1 <= x < 100
x

array([73,  2, 45, 28, 75, 43, 57,  1,  7, 63])

In [23]:
np.random.choice(x, 5, replace=False)

array([75,  2, 73, 63, 45])

- 난수 생성

In [25]:
# random(N) - Uniform 분포, 0~ 1 사이의 값 N개
np.random.random(10)

array([0.36218393, 0.62702939, 0.51488475, 0.89490732, 0.51866543,
       0.60740918, 0.474816  , 0.7095907 , 0.11524271, 0.73279407])

In [26]:
# randint(low, high, N) - [low, high] 범위의 정수 N개
np.random.randint(1, 7, 10) 

array([3, 6, 6, 6, 3, 5, 1, 4, 3, 6])

In [27]:
# normal(평균, 표준편차, N) - 정규분포 N개 
np.random.normal(170, 10, 10)

array([156.53628022, 179.00065486, 165.31670827, 167.70924665,
       183.85559939, 180.5501845 , 171.24584213, 166.70363497,
       168.34700808, 169.12016278])

In [28]:
# randn - 표준정규분포 N(0, 1) N개
np.random.randn(10)

array([-0.41991561,  2.26645028, -0.37412834,  0.08648474,  0.55860069,
        0.54103627, -0.09494843,  0.23191299, -1.27794149, -1.81694754])

In [29]:
# binomial(시도횟수, 평균, N) - 이항분포 N개
np.random.binomial(10, 0.5, 20).reshape(4, 5)

array([[6, 4, 5, 7, 7],
       [4, 5, 4, 6, 3],
       [2, 5, 5, 6, 5],
       [3, 6, 5, 4, 4]])

In [30]:
# 가설검정: t-검정 (1-sample T, 2-sample T, paired T)
# Student t(자유도, N)
np.random.standard_t(2, 10)

array([ 3.16220223,  0.15162527, -0.9639891 ,  0.5706655 ,  1.46715762,
       -0.86149343,  6.61391681, 14.98065979,  0.5572856 ,  0.70375762])

- 연습문제 3.5.1

In [46]:
# 1.동전을 10번 던져 앞면(숫자 1과) 뒷면(숫자 0이) 나오는 가상 실험을 파이썬으로 작성한다.
np.random.randint(2, size=10)




array([0, 0, 0, 0, 1, 0, 0, 1, 1, 1])

In [59]:
# 2. 주사위를 100번 던져서 나오는 숫자의 평균을 구하라.
x = np.random.randint(7, size=100)
x.mean()



2.88

- 연습문제 3.5.2

In [79]:
# 5개만 먼저 테스트
rate = np.random.normal(0, 0.01, 5)
rate

array([0.00967244, 0.00540525, 0.01071849, 0.0062293 , 0.00403768])

In [83]:
price = 10000
for i in range(5):
    price = price * (1  + rate[i])              # price * (1+r)
    price = int(round(price, 0))                # 가격의 단위는 원(소숫점 아래 자리는 버림)
    print(price, end=' ')

10097 10152 10261 10325 10367 

In [86]:
# 250개의 수익률 생성
np.random.seed(2023)
rate = np.random.normal(0, 0.01, 250)
rate[:5]


array([ 0.00711674, -0.00324485, -0.01001871,  0.00236251, -0.0010216 ])

In [87]:
# 1. 리스트로 해결
price = 10000
price_list = []
for i in range(250):
    price = price * (1 + rate[i])
    price = int(round(price, 0)) 
    price_list.append(price)

price_list[-10:]                # 어레이로 만들고 싶으면   np.array(price_list)

[10814, 10893, 10674, 10645, 10588, 10724, 10739, 10686, 10691, 10497]

In [89]:
#  2. 어레이로 해결
price = 10000
price_array = np.empty(250, dtype=int)
for i in range(250):
    price = price * (1 + rate[i])
    price = int(round(price, 0))
    price_array[i] = price

    
price_array[-10:]

array([10814, 10893, 10674, 10645, 10588, 10724, 10739, 10686, 10691,
       10497])

- 데이터 카운팅

In [93]:
np.random.seed(2023)
dices = np.random.randint(1, 7, 100)

In [94]:
# 고유한 값
np.unique(dices)

array([1, 2, 3, 4, 5, 6])

In [95]:
# 고유한 값과 돗수
np.unique(dices, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([16, 18, 13, 15, 19, 19], dtype=int64))

In [96]:
indices, count =np.unique(dices, return_counts=True)
indices * count 

array([ 16,  36,  39,  60,  95, 114], dtype=int64)

In [97]:
# 가중 평균
np.sum(indices * count) / np.sum(count)

3.6

In [98]:
np.mean(dices)

3.6

In [99]:
a = np.array(['x','y','x','y','z','y'])
np.unique(a, return_counts=True)

(array(['x', 'y', 'z'], dtype='<U1'), array([2, 3, 1], dtype=int64))